CREATE TYPE "progress_status" AS ENUM (
  'STARTED',
  'COMPLETED',
  'ARCHIVED'
);

CREATE TYPE "roadmap_status" AS ENUM (
  'DRAFT',
  'PUBLISHED',
  'ARCHIVED'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "avatar_url" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "roadmaps" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "title" varchar NOT NULL,
  "description" text,
  "status" roadmap_status DEFAULT 'DRAFT',
  "content" jsonb NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "node_templates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "name" varchar NOT NULL,
  "base_config" jsonb NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "roadmap_progress" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "roadmap_id" integer,
  "status" progress_status DEFAULT 'STARTED',
  "node_states" jsonb DEFAULT '{}',
  "started_at" timestamp DEFAULT (now()),
  "last_updated" timestamp DEFAULT (now())
);

CREATE TABLE "node_library" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" integer,
  "name" varchar NOT NULL,
  "category" varchar DEFAULT 'General',
  "style_config" jsonb NOT NULL,
  "is_system_default" boolean DEFAULT false
);

CREATE UNIQUE INDEX ON "roadmap_progress" ("user_id", "roadmap_id");

COMMENT ON COLUMN "node_library"."owner_id" IS 'Null if system default';

ALTER TABLE "roadmaps" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "node_templates" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");

ALTER TABLE "roadmap_progress" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "roadmap_progress" ADD FOREIGN KEY ("roadmap_id") REFERENCES "roadmaps" ("id");

ALTER TABLE "node_library" ADD FOREIGN KEY ("owner_id") REFERENCES "users" ("id");
